# Step 1: Modules caching from Node
# Add go.sum later
FROM node:16-alpine as node
WORKDIR /modules
COPY package* .
RUN npm ci

FROM avcosystems/golang-node
WORKDIR /app
COPY . . 
COPY --from=node /modules/node_modules /app/node_modules
RUN go mod download
CMD ["npx", "nodemon", "--exec", "go", "run", "./cmd/app", "-e", "go"]