version: "3.8"

services:
  api-test:
    image: chentex/go-rest-api
    ports:  
      - "8080:8080"
  gomark:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    



